# 基本設定
title: Noraworld Developers Blog
description: >- # この行以降、次のプロパティが登場するまでは複数行の説明文として扱われる
  日々の開発や趣味プログラミングで得た技術的な知見を共有するブログです
url: "https://ja.developers.noraworld.blog"
baseurl: ""

# 今のところはとりあえず使わない
# email: me@example.com
# twitter_username: noraworld_com
# github_username: noraworld

# サイト設定
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# 除外ファイルリスト
## 上の 10 個はデフォルトで除外されるらしいが、一応、除外リストとして明記しておく
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - books/
  - .gitignore
  - README.md
  - mapping.txt

# GitHub Pages で公開する記事の指定
collections:
  articles:
    output: true
    permalink: /:path
